@startuml 1-new-session-with-capacity

title 1) New session with capacity

autonumber
hide footbox

Client -> Ingress: request
activate Ingress
Ingress -> Ingress: check for path match
Ingress -> ServiceProxy: forward request
deactivate Ingress

activate ServiceProxy
ServiceProxy ->X ServiceProxy: check for <b>session-create-block</b> state
ServiceProxy ->X ServiceProxy: check <b>[new_session_count]</b> > <b>[max_new_sessions_per_min]</b>
ServiceProxy -> ServiceProxy: increment <b>[new_session_count]</b> for past minute
ServiceProxy -> ServiceProxy: Add <b>proxy session cookie</b> to header
ServiceProxy -> Resource: forward request

activate Resource
Resource -> Resource: create session
Resource --> ServiceProxy: response
deactivate Resource
ServiceProxy --> Ingress: response
deactivate ServiceProxy
Ingress --> Client: response with <b>proxy session cookie</b>

@enduml