@startuml 2-existing-session

title 2) Existing session

autonumber
hide footbox

Client -> Ingress: request w/ <b>proxy session cookie</b>
activate Ingress

Ingress -> Ingress: check for path match
Ingress -> ServiceProxy: forward request
deactivate Ingress

activate ServiceProxy
ServiceProxy -> ServiceProxy: existing session (valid cookie)
note left: A valid proxy session cookie is always allowed through\nregardless of capacity
ServiceProxy -> Resource: forward request
Resource --> ServiceProxy: response
deactivate ServiceProxy
ServiceProxy --> Ingress: response

Ingress --> Client: response

@enduml