@startuml Waitroom (generic) new session with capacity

title 3) New session reached capacity

autonumber
hide footbox

Client -> Ingress: request

activate Ingress
Ingress ->X Ingress: check for session cookie
Ingress -> SessionRegulator: forward request
deactivate Ingress

activate SessionRegulator
SessionRegulator ->X SessionRegulator: check for <b>session-create-block</b> state
SessionRegulator -> SessionRegulator: check <b>[new_session_count]</b> > <b>[max_new_sessions_per_min]</b>
SessionRegulator -> SessionRegulator: set <b>session-create-block</b> state\n<<timestamp>>
SessionRegulator --> Client: 302 Redirect
deactivate SessionRegulator

Client -> "Static Page": request
"Static Page" --> Client: response
Client -> Client: retry (30 second)

Client -> SessionRegulator: request
activate SessionRegulator
SessionRegulator ->X SessionRegulator: check for session cookie
SessionRegulator -> SessionRegulator: check for <b>session-create-block</b> state
SessionRegulator -> SessionRegulator: expire <b>session-create-block state</b> if\n<b>[current_time]</b> - <b>[session_block_timestamp]</b> > <b>[session_block_duration]</b>
SessionRegulator -> SessionRegulator: clear <b>[new_session_count]</b>
SessionRegulator -> SessionRegulator: increment <b>[new_session_count]</b> for past minute
SessionRegulator -> Resource: forward request
deactivate SessionRegulator

activate Resource
Resource -> Resource: create session
Resource --> Client: response with session cookie
deactivate Resource

@enduml